version: "3"

services:
  # match_making:
  #   build:
  #     context: ./
  #     dockerfile: ./matchmaking/Dockerfile
  #   volumes:
  #     - ~/.aws/credentials:/root/.aws/credentials:ro
  #   env_file: ./matchmaking/service.env


  game_service:
    build: 
      context: ./
      dockerfile: ./game/Dockerfile
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ./game:/game
      - ./common:/game/common
    env_file: ./game/service.env
    environment: 
      - PYTHONUNBUFFERED=1
    ports: 
      - 5000:5000


  # game_cache:
  #   ports: 
  #     - 6379:6379
  #   image: redis:latest


